using System;

namespace BackEndAplication.Models.PHCDBModel
{
    public class Cl
    {
        //public Cl()
        //{
        //    ListaCl = new List<Cl>();
        //}
        public string Clstamp { get; set; }
        public string Nome { get; set; }
        public decimal No { get; set; }
        public decimal Estab { get; set; }
        public string Vendnm { get; set; }
        public string Ncont { get; set; }
        public string Nome2 { get; set; }
        public decimal Saldo { get; set; }
        public decimal Esaldo { get; set; }
        public string Moeda { get; set; }
        public string Fax { get; set; }
        public string Telefone { get; set; }
        public string Contacto { get; set; }
        public decimal Acmfact { get; set; }
        public decimal Eacmfact { get; set; }
        public decimal Rentval { get; set; }
        public decimal Erentval { get; set; }
        public bool Eem { get; set; }
        public decimal Emno { get; set; }
        public bool Eag { get; set; }
        public decimal Agno { get; set; }
        public bool Eid { get; set; }
        public decimal Idno { get; set; }
        public bool Efl { get; set; }
        public decimal Flno { get; set; }
        public decimal Flestab { get; set; }
        public string Morada { get; set; }
        public string Local { get; set; }
        public string Codpost { get; set; }
        public string Zona { get; set; }
        public string Tipo { get; set; }
        public decimal Desconto { get; set; }
        public decimal Vendedor { get; set; }
        public decimal Vencimento { get; set; }
        public decimal Plafond { get; set; }
        public decimal Eplafond { get; set; }
        public string Obs { get; set; }
        public decimal Preco { get; set; }
        public decimal Pais { get; set; }
        public bool Particular { get; set; }
        public string Bino { get; set; }
        public DateTime Bidata { get; set; }
        public string Bilocal { get; set; }
        public string Naturalid { get; set; }
        public string Passaporte { get; set; }
        public string Conta { get; set; }
        public DateTime Nascimento { get; set; }
        public string Pagamento { get; set; }
        public string Cobranca { get; set; }
        public string Nib { get; set; }
        public decimal Descpp { get; set; }
        public string Imagem { get; set; }
        public decimal Odatraso { get; set; }
        public decimal Tabiva { get; set; }
        public string C1Tele { get; set; }
        public string C1Fax { get; set; }
        public string C1Func { get; set; }
        public string C2Tele { get; set; }
        public string C2Fax { get; set; }
        public string C2Func { get; set; }
        public string C2Tacto { get; set; }
        public string C3Tele { get; set; }
        public string C3Fax { get; set; }
        public string C3Func { get; set; }
        public string C3Tacto { get; set; }
        public bool Dqtt { get; set; }
        public bool Clivd { get; set; }
        public string Descarga { get; set; }
        public bool Nocredit { get; set; }
        public string Segmento { get; set; }
        public string Email { get; set; }
        public string Fref { get; set; }
        public string Ccusto { get; set; }
        public string Ncusto { get; set; }
        public bool Naood { get; set; }
        public bool Naomail { get; set; }
        public string Contalet { get; set; }
        public string Contaletdes { get; set; }
        public string Contaletsac { get; set; }
        public decimal Alimite { get; set; }
        public decimal Dqttval { get; set; }
        public string Tipodesc { get; set; }
        public string Tlmvl { get; set; }
        public string Cobrador { get; set; }
        public string Rota { get; set; }
        public string Contaainc { get; set; }
        public string Contaacer { get; set; }
        public string Eancl { get; set; }
        public bool Ediexp { get; set; }
        public string Url { get; set; }
        public string Tpstamp { get; set; }
        public string Tpdesc { get; set; }
        public string Pncont { get; set; }
        public string Cobtele { get; set; }
        public string Cobfax { get; set; }
        public string Cobfunc { get; set; }
        public string Cobtacto { get; set; }
        public string Ollocal { get; set; }
        public decimal Contado { get; set; }
        public string Pscm { get; set; }
        public decimal Zncm { get; set; }
        public decimal Excm { get; set; }
        public string Ptcm { get; set; }
        public string Encm { get; set; }
        public decimal Ntcm { get; set; }
        public string Pscmdesc { get; set; }
        public string Znregiao { get; set; }
        public string Excmdesc { get; set; }
        public string Ptcmdesc { get; set; }
        public string Encmdesc { get; set; }
        public bool Usaintra { get; set; }
        public bool Cobnao { get; set; }
        public decimal Saldlet { get; set; }
        public decimal Esaldlet { get; set; }
        public string Site { get; set; }
        public string Bizzaddress { get; set; }
        public decimal Bizzproto { get; set; }
        public string Cass { get; set; }
        public string Classe { get; set; }
        public string Lang { get; set; }
        public bool Iectisento { get; set; }
        public string Niec { get; set; }
        public string Gaenome { get; set; }
        public string Gaecstamp { get; set; }
        public bool Clinica { get; set; }
        public bool Ftndias { get; set; }
        public string Txftndias { get; set; }
        public bool Ftdiasmr { get; set; }
        public string Txftdias { get; set; }
        public bool Ftdatasmr { get; set; }
        public string Txftdata { get; set; }
        public bool Ftnid { get; set; }
        public string Txftnid { get; set; }
        public bool Ftidnome { get; set; }
        public string Txftidnome { get; set; }
        public bool Ftidcontacto { get; set; }
        public string Txftidcontacto { get; set; }
        public bool Ftidnac { get; set; }
        public string Txftidnac { get; set; }
        public bool Ftidcont { get; set; }
        public string Txftidcont { get; set; }
        public bool Ftidutente { get; set; }
        public string Txftidutente { get; set; }
        public bool Ftidbi { get; set; }
        public string Txftidbi { get; set; }
        public bool Ftidcob { get; set; }
        public string Txftidcob { get; set; }
        public bool Ftmrtot { get; set; }
        public string Txftmrtot { get; set; }
        public bool Ftumamr { get; set; }
        public bool Paramr { get; set; }
        public bool Filtrast { get; set; }
        public string Contatit { get; set; }
        public string Statuspda { get; set; }
        public bool Inactivo { get; set; }
        public bool Naoencomenda { get; set; }
        public bool Clifactor { get; set; }
        public string Contafac { get; set; }
        public bool Dfront { get; set; }
        public bool Dsuporte { get; set; }
        public bool Dformacao { get; set; }
        public bool Dteam { get; set; }
        public bool Recdocdig { get; set; }
        public string Glncl { get; set; }
        public string Codfornecedor { get; set; }
        public string Localentrega { get; set; }
        public string Obsdoc { get; set; }
        public bool Ecoisento { get; set; }
        public string Tbprcod { get; set; }
        public string Area { get; set; }
        public bool Exporpos { get; set; }
        public bool Temcred { get; set; }
        public bool Temftglob { get; set; }
        public decimal Ltyp { get; set; }
        public decimal Lmlt { get; set; }
        public decimal Rbal { get; set; }
        public bool Addd { get; set; }
        public string Id { get; set; }
        public string Track { get; set; }
        public decimal Tracknr { get; set; }
        public string Pin { get; set; }
        public string Encrpin { get; set; }
        public bool Blck { get; set; }
        public decimal Acc { get; set; }
        public bool Repl { get; set; }
        public bool Odo { get; set; }
        public bool Did { get; set; }
        public bool Carr { get; set; }
        public string Fuels { get; set; }
        public bool Cw { get; set; }
        public string Shop { get; set; }
        public string Refcli { get; set; }
        public string Matric { get; set; }
        public decimal Desccmb { get; set; }
        public decimal Descloj { get; set; }
        public string Ousrinis { get; set; }
        public DateTime Ousrdata { get; set; }
        public string Ousrhora { get; set; }
        public string Usrinis { get; set; }
        public DateTime Usrdata { get; set; }
        public string Usrhora { get; set; }
        public bool Marcada { get; set; }
        public bool Isperson { get; set; }
        public decimal Radicaltipoemp { get; set; }
        public bool Autofact { get; set; }
        public string Numcontrepres { get; set; }
        public string Codprovincia { get; set; }
        public bool Autorizacaoactiva { get; set; }
        public string Numautorizacaosdd { get; set; }
        public decimal Numseqaut { get; set; }
        public string Mesesnaopag { get; set; }
        public string Diaspag { get; set; }
        public bool Cancpos { get; set; }
        public string Descregiva { get; set; }
        public string C1Email { get; set; }
        public string C2Email { get; set; }
        public string C3Email { get; set; }
        public string Cobemail { get; set; }
        public DateTime Pcktsyncdate { get; set; }
        public string Pcktsynctime { get; set; }
        public string Motiseimp { get; set; }
        public string Codmotiseimp { get; set; }
        public string Distrito { get; set; }
        public bool Ccadmin { get; set; }
        public bool Geramb { get; set; }

        //public virtual ICollection<Cl> ListaCl { get; set; }
    }
}