using System;

namespace BackEndAplication.Models.PHCDBModel
{
    public class Ts
    {
        public string Tsstamp { get; set; }
        public decimal Ndos { get; set; }
        public string Nmdos { get; set; }
        public decimal Cmstocks { get; set; }
        public string Cmdesc { get; set; }
        public string Nmdosp { get; set; }
        public string Nmdosa { get; set; }
        public string Bdempresas { get; set; }
        public string Preco1 { get; set; }
        public string Preco2 { get; set; }
        public string Qtt1 { get; set; }
        public string Qtt2 { get; set; }
        public bool Stocks { get; set; }
        public string Impressao { get; set; }
        public string Texto1 { get; set; }
        public string Texto2 { get; set; }
        public string Texto3 { get; set; }
        public string Tvendno { get; set; }
        public string Tnopat { get; set; }
        public string Tnomquina { get; set; }
        public string Ttecnico { get; set; }
        public string Tmodelo { get; set; }
        public string Tmarca { get; set; }
        public string Tserie { get; set; }
        public bool Rescli { get; set; }
        public bool Resfor { get; set; }
        public bool Resrec { get; set; }
        public string Tipo1 { get; set; }
        public string Tipo2 { get; set; }
        public string Tipo3 { get; set; }
        public string Tipo4 { get; set; }
        public bool Desconto { get; set; }
        public decimal Qttdec { get; set; }
        public bool Q2Qst { get; set; }
        public string Ldata { get; set; }
        public string Dedata { get; set; }
        public string Atedata { get; set; }
        public string Lobs { get; set; }
        public string Litem { get; set; }
        public decimal Predec { get; set; }
        public string Nmdatafim { get; set; }
        public string Nmdesc { get; set; }
        public bool Mexenumero { get; set; }
        public bool Copiad { get; set; }
        public bool Noref { get; set; }
        public bool Passref { get; set; }
        public decimal Qpreco { get; set; }
        public decimal Qprecocusto { get; set; }
        public string Nmdtopen { get; set; }
        public bool Valor2 { get; set; }
        public string Lobs2 { get; set; }
        public string Litem2 { get; set; }
        public bool Clitem2 { get; set; }
        public string Lobs3 { get; set; }
        public bool Resusr { get; set; }
        public bool Trfa { get; set; }
        public decimal Cm2Stocks { get; set; }
        public string Cm2Desc { get; set; }
        public bool Usaiva { get; set; }
        public bool Producao { get; set; }
        public bool Actprod { get; set; }
        public bool Avenca { get; set; }
        public bool Tabfor { get; set; }
        public string Tabela1 { get; set; }
        public bool Lsto { get; set; }
        public bool Lprev { get; set; }
        public bool Lcli { get; set; }
        public bool Lfor { get; set; }
        public bool Lsta { get; set; }
        public bool Ldescli { get; set; }
        public string Logi3 { get; set; }
        public string Logi4 { get; set; }
        public string Logi5 { get; set; }
        public string Logi6 { get; set; }
        public string Logi7 { get; set; }
        public string Logi8 { get; set; }
        public string Logi1 { get; set; }
        public string Logi2 { get; set; }
        public bool Evend { get; set; }
        public bool Grelha { get; set; }
        public bool Usam2 { get; set; }
        public bool Usam3 { get; set; }
        public bool Etecn { get; set; }
        public bool Comstk { get; set; }
        public bool Usam1 { get; set; }
        public bool Lifref { get; set; }
        public bool Infref { get; set; }
        public bool Outref { get; set; }
        public bool Uni2 { get; set; }
        public bool Uni3 { get; set; }
        public bool Noconv { get; set; }
        public bool Convarr { get; set; }
        public decimal Armazem { get; set; }
        public bool Refarm { get; set; }
        public bool Saldebito { get; set; }
        public bool Saldesc { get; set; }
        public bool Reflinha { get; set; }
        public bool Salref { get; set; }
        public bool Qttum { get; set; }
        public bool Boavst { get; set; }
        public bool Stneg { get; set; }
        public decimal Cambio { get; set; }
        public string Linum1 { get; set; }
        public string Linum2 { get; set; }
        public bool Composto { get; set; }
        public bool Compnovo { get; set; }
        public bool Compcusto { get; set; }
        public bool Lplafond { get; set; }
        public bool Dividas { get; set; }
        public bool Ttconf { get; set; }
        public string Lotedef { get; set; }
        public bool Stdesc { get; set; }
        public bool Valqtt { get; set; }
        public decimal Valpct1 { get; set; }
        public decimal Valpct2 { get; set; }
        public string Valpass { get; set; }
        public bool Actpromo { get; set; }
        public bool Igdata { get; set; }
        public DateTime Datafech { get; set; }
        public string Ndosimp { get; set; }
        public bool Confdesc { get; set; }
        public bool Confprec { get; set; }
        public bool Usausr6 { get; set; }
        public bool Usasemaf { get; set; }
        public bool Actpv { get; set; }
        public bool Actpcusto { get; set; }
        public bool Ncin { get; set; }
        public bool Ncout { get; set; }
        public bool Sattotal { get; set; }
        public bool Usatclass { get; set; }
        public string Posic { get; set; }
        public bool Iproposta { get; set; }
        public bool Plaflet { get; set; }
        public decimal Ndescs { get; set; } //=>este o campo a ir buscar
        public bool Livendedor { get; set; }
        public string Xddesc { get; set; }
        public string Xdstamp { get; set; }
        public string Infosdos { get; set; }
        public string Infoster { get; set; }
        public bool Refma { get; set; }
        public bool Foserie { get; set; }
        public bool Ftserie { get; set; }
        public bool Veserie { get; set; }
        public bool Ctrequi { get; set; }
        public bool Trfarm { get; set; }
        public bool Retequi { get; set; }
        public decimal Ocupacao { get; set; }
        public bool Qulinhas { get; set; }
        public bool Overbooking { get; set; }
        public bool Tccusto { get; set; }
        public bool Tncusto { get; set; }
        public string Tabela2 { get; set; }
        public bool Temefront { get; set; }
        public bool Temsupext { get; set; }
        public bool Avisaqtt { get; set; }
        public string Avisatdos { get; set; }
        public string Tipodos { get; set; }
        public bool Lib { get; set; }
        public string Adjnm { get; set; }
        public bool Usasit { get; set; }
        public string Fami { get; set; }
        public string Pctfami { get; set; }
        public bool Ltabs { get; set; }
        public decimal Ndecomp { get; set; }
        public decimal Passis { get; set; }
        public string Nmdos2 { get; set; }
        public decimal Ndos2 { get; set; }
        public bool Usaieca { get; set; }
        public bool Orcamento { get; set; }
        public bool Oci { get; set; }
        public bool Pedidopv { get; set; }
        public bool Seproj { get; set; }
        public bool Custoreal { get; set; }
        public bool Tbrmais { get; set; }
        public bool Tbrmenos { get; set; }
        public bool Medicao { get; set; }
        public string Nmdoc1 { get; set; }
        public string Nmdoc2 { get; set; }
        public string Nmdoc3 { get; set; }
        public string Nmdosmais { get; set; }
        public string Nmdosmenos { get; set; }
        public bool Tabsede { get; set; }
        public bool Frota { get; set; }
        public bool Uticonf { get; set; }
        public string Nmconf { get; set; }
        public bool Altefront { get; set; }
        public bool Usafornec { get; set; }
        public bool Cativo { get; set; }
        public bool Corst { get; set; }
        public bool Corstpla { get; set; }
        public bool Mstcomp { get; set; }
        public bool Pstcomp { get; set; }
        public bool Vaihist { get; set; }
        public bool Actforn { get; set; }
        public bool Showflnmincl { get; set; }
        public decimal Tacesso { get; set; }
        public decimal Userno { get; set; }
        public string Usernm { get; set; }
        public string Acesso { get; set; }
        public string Tabela { get; set; }
        public decimal Pfcod { get; set; }
        public string Pfnm { get; set; }
        public string Aprovado { get; set; }
        public bool Controlacopia { get; set; }
        public bool Altaprov { get; set; }
        public bool Impedeimp { get; set; }
        public bool Ecovalor { get; set; }
        public bool Ecovalormapa { get; set; }
        public bool Naoencomenda { get; set; }
        public bool Retiracusto { get; set; }
        public decimal Pvmoedec { get; set; }
        public bool Negocios { get; set; }
        public bool Biseries { get; set; }
        public bool Usatabfor { get; set; }
        public bool Usaldescli { get; set; }
        public bool Actprodclc { get; set; }
        public bool Actprodclp { get; set; }
        public string Ousrinis { get; set; }
        public DateTime Ousrdata { get; set; }
        public string Ousrhora { get; set; }
        public string Usrinis { get; set; }
        public DateTime Usrdata { get; set; }
        public string Usrhora { get; set; }
        public bool Marcada { get; set; }
    }
}