using System;

namespace ConnectorService.Model.PHCModel
{
    public class Bi
    {
        //public Bi()
        //{
        //    ListaBis = new List<Bi>();
        //}
		
		
        public string Bistamp { get; set; }
        public string Nmdos { get; set; }
        public decimal Obrano { get; set; }
        public string Referencia { get; set; }
        public string Design { get; set; }
        public decimal Qtt { get; set; }
        public decimal Qtt2 { get; set; }
        public decimal Iva { get; set; }
        public decimal Tabiva { get; set; }
        public decimal Armazem { get; set; }
        public decimal Pu { get; set; }
        public decimal Debito { get; set; }
        public decimal Prorc { get; set; }
        public decimal Stipo { get; set; }
        public decimal No { get; set; }
        public decimal Pcusto { get; set; }
        public string Serie { get; set; }
        public decimal Nomquina { get; set; }
        public decimal Nopat { get; set; }
        public decimal Fno { get; set; }
        public DateTime Fdata { get; set; }
        public string Nmdoc { get; set; }
        public decimal Ndoc { get; set; }
        public decimal Ndos { get; set; }
        public string Forref { get; set; }
        public decimal Txiva { get; set; }
        public DateTime Rdata { get; set; }
        public DateTime Dedata { get; set; }
        public DateTime Atedata { get; set; }
        public string Lobs { get; set; }
        public decimal Ldossier { get; set; }
        public string Obranome { get; set; }
        public bool Fechada { get; set; }
        public DateTime Datafinal { get; set; }
        public DateTime Dataobra { get; set; }
        public DateTime Dataopen { get; set; }
        public DateTime Datafecho { get; set; }
        public decimal Tecnico { get; set; }
        public string Maquina { get; set; }
        public string Marca { get; set; }
        public string Zona { get; set; }
        public string Litem { get; set; }
        public decimal Vumoeda { get; set; }
        public bool Resfor { get; set; }
        public bool Rescli { get; set; }
        public bool Resrec { get; set; }
        public bool Iprint { get; set; }
        public string Lobs2 { get; set; }
        public string Litem2 { get; set; }
        public string Lobs3 { get; set; }
        public decimal Estab { get; set; }
        public bool Resusr { get; set; }
        public decimal Ar2Mazem { get; set; }
        public bool Composto { get; set; }
        public bool Compostoori { get; set; }
        public string Lrecno { get; set; }
        public decimal Lordem { get; set; }
        public bool Fmarcada { get; set; }
        public bool Producao { get; set; }
        public string Local { get; set; }
        public string Morada { get; set; }
        public string Codpost { get; set; }
        public string Nome { get; set; }
        public decimal Vendedor { get; set; }
        public string Vendnm { get; set; }
        public bool Tabfor { get; set; }
        public string Tabela1 { get; set; }
        public bool Descli { get; set; }
        public string Reff { get; set; }
        public string Lote { get; set; }
        public bool Ivaincl { get; set; }
        public string Cor { get; set; }
        public string Tam { get; set; }
        public string Segmento { get; set; }
        public string Bofref { get; set; }
        public string Bifref { get; set; }
        public decimal Grau { get; set; }
        public decimal Partes { get; set; }
        public decimal Partes2 { get; set; }
        public decimal Altura { get; set; }
        public decimal Largura { get; set; }
        public decimal Espessura { get; set; }
        public string Biserie { get; set; }
        public bool Infref { get; set; }
        public bool Lifref { get; set; }
        public decimal Uni2Qtt { get; set; }
        public decimal Epu { get; set; }
        public decimal Edebito { get; set; }
        public decimal Eprorc { get; set; }
        public decimal Epcusto { get; set; }
        public decimal Ttdeb { get; set; }
        public decimal Ettdeb { get; set; }
        public decimal Ttmoeda { get; set; }
        public string Adoc { get; set; }
        public decimal Binum1 { get; set; }
        public decimal Binum2 { get; set; }
        public string Codigo { get; set; }
        public decimal Cpoc { get; set; }
        public bool Stns { get; set; }
        public string Obistamp { get; set; }
        public string Oobistamp { get; set; }
        public string Usr1 { get; set; }
        public string Usr2 { get; set; }
        public string Usr3 { get; set; }
        public string Usr4 { get; set; }
        public string Usr5 { get; set; }
        public string Usr6 { get; set; }
        public bool Usalote { get; set; }
        public bool Texteis { get; set; }
        public string Unidade { get; set; }
        public string Unidad2 { get; set; }
        public string Oftstamp { get; set; }
        public string Ofostamp { get; set; }
        public bool Promo { get; set; }
        public bool Epromo { get; set; }
        public string Familia { get; set; }
        public bool Sattotal { get; set; }
        public bool Noserie { get; set; }
        public decimal Slvu { get; set; }
        public decimal Eslvu { get; set; }
        public decimal Sltt { get; set; }
        public decimal Esltt { get; set; }
        public decimal Slvumoeda { get; set; }
        public decimal Slttmoeda { get; set; }
        public decimal Ncmassa { get; set; }
        public decimal Ncunsup { get; set; }
        public decimal Ncvest { get; set; }
        public decimal Encvest { get; set; }
        public string Nccod { get; set; }
        public string Ncinteg { get; set; }
        public decimal Classif { get; set; }
        public string Classifc { get; set; }
        public string Posic { get; set; }
        public decimal Desconto { get; set; }
        public decimal Desc2 { get; set; }
        public decimal Desc3 { get; set; }
        public decimal Desc4 { get; set; }
        public decimal Desc5 { get; set; }
        public decimal Desc6 { get; set; }
        public string Series { get; set; }
        public string Series2 { get; set; }
        public string Ccusto { get; set; }
        public string Ncusto { get; set; }
        public decimal Num1 { get; set; }
        public bool Fechabo { get; set; }
        public string Oobostamp { get; set; }
        public string Ltab1 { get; set; }
        public string Ltab2 { get; set; }
        public string Ltab3 { get; set; }
        public string Ltab4 { get; set; }
        public string Ltab5 { get; set; }
        public string Fami { get; set; }
        public decimal Pctfami { get; set; }
        public bool Adjudicada { get; set; }
        public decimal Tieca { get; set; }
        public decimal Etieca { get; set; }
        public decimal Mtieca { get; set; }
        public decimal Volume { get; set; }
        public bool Iecasug { get; set; }
        public decimal Iecagrad { get; set; }
        public string Iecacodisen { get; set; }
        public decimal Peso { get; set; }
        public decimal Pbruto { get; set; }
        public string Codfiscal { get; set; }
        public string Dgeral { get; set; }
        public bool Temoci { get; set; }
        public bool Temomi { get; set; }
        public bool Temsubemp { get; set; }
        public decimal Encargo { get; set; }
        public decimal Eencargo { get; set; }
        public decimal Custoind { get; set; }
        public decimal Ecustoind { get; set; }
        public string Tiposemp { get; set; }
        public bool Pvok { get; set; }
        public bool Boclose { get; set; }
        public DateTime Dtclose { get; set; }
        public string Quarto { get; set; }
        public bool Emconf { get; set; }
        public string Efornecedor { get; set; }
        public decimal Efornec { get; set; }
        public decimal Efornestab { get; set; }
        public bool Cativo { get; set; }
        public string Optstamp { get; set; }
        public string Oristamp { get; set; }
        public bool Temeco { get; set; }
        public decimal Ecoval { get; set; }
        public decimal Eecoval { get; set; }
        public decimal Tecoval { get; set; }
        public decimal Etecoval { get; set; }
        public decimal Ecoval2 { get; set; }
        public decimal Eecoval2 { get; set; }
        public decimal Tecoval2 { get; set; }
        public decimal Etecoval2 { get; set; }
        public bool Econotcalc { get; set; }
        public string Bostamp { get; set; }
        public string Ousrinis { get; set; }
        public DateTime Ousrdata { get; set; }
        public string Ousrhora { get; set; }
        public string Usrinis { get; set; }
        public DateTime Usrdata { get; set; }
        public string Usrhora { get; set; }
        public bool Marcada { get; set; }
        public bool Mntencargos { get; set; }
        public decimal Debitoori { get; set; }
        public decimal Edebitoori { get; set; }
        public bool Trocaequi { get; set; }
        public decimal Tpromo { get; set; }
        public decimal Valdesc { get; set; }
        public decimal Evaldesc { get; set; }


        //public virtual ICollection<Bi> ListaBis { get; set; }
    }
}