using System;

namespace ConnectorService.Model.PHCModel
{
    public class Bo
    {
        //public Bo()
        //{
        //    ListaBos = new List<Bo>();
        //}
        public string Bostamp { get; set; }
        public string Nmdos { get; set; }
        public decimal Obrano { get; set; }
        public DateTime Dataobra { get; set; }
        public string Nome { get; set; }
        public decimal Totaldeb { get; set; }
        public decimal Etotaldeb { get; set; }
        public string Tipo { get; set; }
        public DateTime Datafinal { get; set; }
        public decimal Smoe4 { get; set; }
        public decimal Smoe3 { get; set; }
        public decimal Smoe2 { get; set; }
        public decimal Smoe1 { get; set; }
        public decimal Moetotal { get; set; }
        public decimal Sdeb2 { get; set; }
        public decimal Sdeb1 { get; set; }
        public decimal Sdeb4 { get; set; }
        public decimal Sdeb3 { get; set; }
        public decimal Sqtt14 { get; set; }
        public decimal Sqtt13 { get; set; }
        public decimal Sqtt12 { get; set; }
        public decimal Sqtt11 { get; set; }
        public decimal Sqtt24 { get; set; }
        public decimal Sqtt23 { get; set; }
        public decimal Sqtt22 { get; set; }
        public decimal Sqtt21 { get; set; }
        public decimal Vqtt24 { get; set; }
        public decimal Vqtt23 { get; set; }
        public decimal Vqtt22 { get; set; }
        public decimal Vqtt21 { get; set; }
        public decimal Vendedor { get; set; }
        public string Vendnm { get; set; }
        public decimal Stot1 { get; set; }
        public decimal Stot2 { get; set; }
        public decimal Stot3 { get; set; }
        public decimal Stot4 { get; set; }
        public decimal No { get; set; }
        public string Obranome { get; set; }
        public decimal Boano { get; set; }
        public DateTime Dataopen { get; set; }
        public DateTime Datafecho { get; set; }
        public bool Fechada { get; set; }
        public decimal Nopat { get; set; }
        public decimal Total { get; set; }
        public decimal Tecnico { get; set; }
        public string Tecnnm { get; set; }
        public decimal Nomquina { get; set; }
        public string Maquina { get; set; }
        public string Marca { get; set; }
        public string Serie { get; set; }
        public string Zona { get; set; }
        public string Obs { get; set; }
        public string Trab1 { get; set; }
        public string Trab2 { get; set; }
        public string Trab3 { get; set; }
        public string Trab4 { get; set; }
        public string Trab5 { get; set; }
        public decimal Ndos { get; set; }
        public decimal Custo { get; set; }
        public string Moeda { get; set; }
        public decimal Estab { get; set; }
        public string Morada { get; set; }
        public string Local { get; set; }
        public string Codpost { get; set; }
        public DateTime Ultfact { get; set; }
        public decimal Period { get; set; }
        public string Tabela1 { get; set; }
        public string Ncont { get; set; }
        public bool Logi1 { get; set; }
        public bool Logi2 { get; set; }
        public bool Logi3 { get; set; }
        public bool Logi4 { get; set; }
        public bool Logi5 { get; set; }
        public bool Logi6 { get; set; }
        public bool Logi7 { get; set; }
        public bool Logi8 { get; set; }
        public string Segmento { get; set; }
        public bool Impresso { get; set; }
        public string Userimpresso { get; set; }
        public string Fref { get; set; }
        public string Ccusto { get; set; }
        public string Ncusto { get; set; }
        public string Cobranca { get; set; }
        public bool Infref { get; set; }
        public bool Lifref { get; set; }
        public decimal Esdeb1 { get; set; }
        public decimal Esdeb2 { get; set; }
        public decimal Esdeb3 { get; set; }
        public decimal Esdeb4 { get; set; }
        public decimal Evqtt21 { get; set; }
        public decimal Evqtt22 { get; set; }
        public decimal Evqtt23 { get; set; }
        public decimal Evqtt24 { get; set; }
        public decimal Estot1 { get; set; }
        public decimal Estot2 { get; set; }
        public decimal Estot3 { get; set; }
        public decimal Estot4 { get; set; }
        public decimal Etotal { get; set; }
        public decimal Ecusto { get; set; }
        public decimal Bo2Tdesc1 { get; set; }
        public decimal Bo2Tdesc2 { get; set; }
        public decimal Ebo2Tdes1 { get; set; }
        public decimal Ebo2Tdes2 { get; set; }
        public decimal Descc { get; set; }
        public decimal Edescc { get; set; }
        public decimal Bo1Tvall { get; set; }
        public decimal Bo2Tvall { get; set; }
        public decimal Ebo1Tvall { get; set; }
        public decimal Ebo2Tvall { get; set; }
        public decimal Bo11Bins { get; set; }
        public decimal Bo11Iva { get; set; }
        public decimal Ebo11Bins { get; set; }
        public decimal Ebo11Iva { get; set; }
        public decimal Bo21Bins { get; set; }
        public decimal Bo21Iva { get; set; }
        public decimal Ebo21Bins { get; set; }
        public decimal Ebo21Iva { get; set; }
        public decimal Bo31Bins { get; set; }
        public decimal Bo31Iva { get; set; }
        public decimal Ebo31Bins { get; set; }
        public decimal Ebo31Iva { get; set; }
        public decimal Bo41Bins { get; set; }
        public decimal Bo41Iva { get; set; }
        public decimal Ebo41Bins { get; set; }
        public decimal Ebo41Iva { get; set; }
        public decimal Bo51Bins { get; set; }
        public decimal Bo51Iva { get; set; }
        public decimal Ebo51Bins { get; set; }
        public decimal Ebo51Iva { get; set; }
        public decimal Bo61Bins { get; set; }
        public decimal Bo61Iva { get; set; }
        public decimal Ebo61Bins { get; set; }
        public decimal Ebo61Iva { get; set; }
        public decimal Bo12Bins { get; set; }
        public decimal Bo12Iva { get; set; }
        public decimal Ebo12Bins { get; set; }
        public decimal Ebo12Iva { get; set; }
        public decimal Bo22Bins { get; set; }
        public decimal Bo22Iva { get; set; }
        public decimal Ebo22Bins { get; set; }
        public decimal Ebo22Iva { get; set; }
        public decimal Bo32Bins { get; set; }
        public decimal Bo32Iva { get; set; }
        public decimal Ebo32Bins { get; set; }
        public decimal Ebo32Iva { get; set; }
        public decimal Bo42Bins { get; set; }
        public decimal Bo42Iva { get; set; }
        public decimal Ebo42Bins { get; set; }
        public decimal Ebo42Iva { get; set; }
        public decimal Bo52Bins { get; set; }
        public decimal Bo52Iva { get; set; }
        public decimal Ebo52Bins { get; set; }
        public decimal Ebo52Iva { get; set; }
        public decimal Bo62Bins { get; set; }
        public decimal Bo62Iva { get; set; }
        public decimal Ebo62Bins { get; set; }
        public decimal Ebo62Iva { get; set; }
        public decimal BoTotp1 { get; set; }
        public decimal BoTotp2 { get; set; }
        public decimal EboTotp1 { get; set; }
        public decimal EboTotp2 { get; set; }
        public bool Edi { get; set; }
        public string Memissao { get; set; }
        public string Nome2 { get; set; }
        public string Pastamp { get; set; }
        public string Snstamp { get; set; }
        public string Mastamp { get; set; }
        public string Origem { get; set; }
        public decimal Orinopat { get; set; }
        public bool Iiva { get; set; }
        public bool Iunit { get; set; }
        public bool Itotais { get; set; }
        public bool Iunitiva { get; set; }
        public bool Itotaisiva { get; set; }
        public string Site { get; set; }
        public string Pnome { get; set; }
        public decimal Pno { get; set; }
        public string Cxstamp { get; set; }
        public string Cxusername { get; set; }
        public string Ssstamp { get; set; }
        public string Ssusername { get; set; }
        public bool Alldescli { get; set; }
        public bool Alldesfor { get; set; }
        public string Series { get; set; }
        public string Series2 { get; set; }
        public string Quarto { get; set; }
        public decimal Ocupacao { get; set; }
        public string Tabela2 { get; set; }
        public string Obstab2 { get; set; }
        public string Iemail { get; set; }
        public string Inome { get; set; }
        public decimal Situacao { get; set; }
        public string Lang { get; set; }
        public string Ean { get; set; }
        public string Iecacodisen { get; set; }
        public bool Boclose { get; set; }
        public DateTime Dtclose { get; set; }
        public string Tpstamp { get; set; }
        public string Tpdesc { get; set; }
        public bool Emconf { get; set; }
        public string Statuspda { get; set; }
        public bool Aprovado { get; set; }
        public decimal Boid { get; set; }
        public string Ousrinis { get; set; }
        public DateTime Ousrdata { get; set; }
        public string Ousrhora { get; set; }
        public string Usrinis { get; set; }
        public DateTime Usrdata { get; set; }
        public string Usrhora { get; set; }
        public bool Marcada { get; set; }

       // public virtual ICollection<Bo> ListaBos { get; set; }
    }
}