using System;

namespace ConnectorService.Model.PHCModel
{
    public class Bo2
    {
        //public Bo2()
        //{
        //    ListaBo2 = new List<Bo2>();
        //}

        public string Bo2Stamp { get; set; }
        public string Pscm { get; set; }
        public decimal Zncm { get; set; }
        public decimal Excm { get; set; }
        public string Ptcm { get; set; }
        public string Encm { get; set; }
        public decimal Ntcm { get; set; }
        public string Pscmdesc { get; set; }
        public string Znregiao { get; set; }
        public string Excmdesc { get; set; }
        public string Ptcmdesc { get; set; }
        public string Encmdesc { get; set; }
        public bool Ncin { get; set; }
        public bool Ncout { get; set; }
        public bool Usaintra { get; set; }
        public decimal Ettieca { get; set; }
        public decimal Ttieca { get; set; }
        public decimal Mttieca { get; set; }
        public bool Iectisento { get; set; }
        public string Adjbostamp { get; set; }
        public string Processo { get; set; }
        public string Subproc { get; set; }
        public bool Adjudicado { get; set; }
        public bool Orcamento { get; set; }
        public decimal Mcomercial { get; set; }
        public string Dpedidopv { get; set; }
        public bool Autos { get; set; }
        public decimal Autotipo { get; set; }
        public decimal Autoper { get; set; }
        public decimal Mensaldia { get; set; }
        public decimal Vencimento { get; set; }
        public decimal Autono { get; set; }
        public bool Tbrsemmed { get; set; }
        public decimal Pdtipo { get; set; }
        public bool Planeamento { get; set; }
        public string Calistamp { get; set; }
        public string Tipoobra { get; set; }
        public string Descobra { get; set; }
        public bool Sujrvp { get; set; }
        public decimal Ttecoval { get; set; }
        public decimal Ettecoval { get; set; }
        public string Ngstamp { get; set; }
        public string Negocio { get; set; }
        public string Descnegocio { get; set; }
        public string Ngstatus { get; set; }
        public string Ousrinis { get; set; }
        public DateTime Ousrdata { get; set; }
        public string Ousrhora { get; set; }
        public string Usrinis { get; set; }
        public DateTime Usrdata { get; set; }
        public string Usrhora { get; set; }
        public bool Marcada { get; set; }
        public string Autobostamp { get; set; }
        public decimal Bo71Bins { get; set; }
        public decimal Bo71Iva { get; set; }
        public decimal Ebo71Bins { get; set; }
        public decimal Ebo71Iva { get; set; }
        public decimal Bo81Bins { get; set; }
        public decimal Bo81Iva { get; set; }
        public decimal Ebo81Bins { get; set; }
        public decimal Ebo81Iva { get; set; }
        public decimal Bo91Bins { get; set; }
        public decimal Bo91Iva { get; set; }
        public decimal Ebo91Bins { get; set; }
        public decimal Ebo91Iva { get; set; }
        public decimal Bo72Bins { get; set; }
        public decimal Bo72Iva { get; set; }
        public decimal Ebo72Bins { get; set; }
        public decimal Ebo72Iva { get; set; }
        public decimal Bo82Bins { get; set; }
        public decimal Bo82Iva { get; set; }
        public decimal Ebo82Bins { get; set; }
        public decimal Ebo82Iva { get; set; }
        public decimal Bo92Bins { get; set; }
        public decimal Bo92Iva { get; set; }
        public decimal Ebo92Bins { get; set; }
        public decimal Ebo92Iva { get; set; }
        public string Alvstamp1 { get; set; }
        public string Identificacao1 { get; set; }
        public string Szzstamp1 { get; set; }
        public string Zona1 { get; set; }
        public string Alvstamp2 { get; set; }
        public string Identificacao2 { get; set; }
        public string Szzstamp2 { get; set; }
        public string Zona2 { get; set; }
        public decimal Armazem { get; set; }
        public decimal Ar2Mazem { get; set; }
        public string Dprocesso { get; set; }
        public decimal Diasde { get; set; }
        public decimal Diasate { get; set; }
        public decimal Ttecoval2 { get; set; }
        public decimal Ettecoval2 { get; set; }
        public decimal Nopkng { get; set; }
        public string Xpdviatura { get; set; }
        public DateTime Xpddata { get; set; }
        public string Xpdhora { get; set; }
        public string Versaocrono { get; set; }
        public string Crpstamp { get; set; }
        public bool Exportado { get; set; }
        public string Cladrsdesc { get; set; }
        public string Morada { get; set; }
        public string Local { get; set; }
        public string Codpost { get; set; }
        public string Cladrszona { get; set; }
        public string Telefone { get; set; }
        public string Contacto { get; set; }
        public string Email { get; set; }
        public string Cladrsstamp { get; set; }
        public string Area { get; set; }
        public string Nomects { get; set; }
        public decimal Nocts { get; set; }
        public decimal Tkhtyp { get; set; }
        public string Tkhcarr { get; set; }
        public string Tkhref { get; set; }
        public decimal EftaxamtA { get; set; }
        public decimal EftaxamtB { get; set; }
        public decimal FtaxamtA { get; set; }
        public decimal FtaxamtB { get; set; }
        public string Tkhhora { get; set; }
        public DateTime Tkhdata { get; set; }
        public string Tkhlref { get; set; }
        public decimal Tkhshf { get; set; }
        public string Tkhopid { get; set; }
        public decimal Tkhltyp { get; set; }
        public decimal Tkhlpnt { get; set; }
        public string Tkhid { get; set; }
        public string Tkhpan { get; set; }
        public decimal Tkhodo { get; set; }
        public decimal Tkhdid { get; set; }
        public string Tkhsttnr { get; set; }
        public string Tkhposcstamp { get; set; }
        public string Pscmori { get; set; }
        public string Pscmoridesc { get; set; }
        public decimal Mtotalciva { get; set; }
        public decimal Etotalciva { get; set; }
        public decimal Totalciva { get; set; }
        public decimal Etotiva { get; set; }
        public decimal Totiva { get; set; }
        public decimal Mtotiva { get; set; }
        public bool Cambiofixo { get; set; }
        public decimal Cambio { get; set; }
        public string Assinatura { get; set; }
        public string Versaochave { get; set; }
        public bool Reorcamento { get; set; }
        public string Stamporcamento { get; set; }
        public decimal Obranoorcamento { get; set; }
        public string Versaorcamento { get; set; }
        public decimal Custototalorc { get; set; }
        public decimal Ecustototalorc { get; set; }
        public decimal Custototalreorc { get; set; }
        public decimal Ecustototalreorc { get; set; }
        public decimal Custototaldif { get; set; }
        public decimal Ecustototaldif { get; set; }
        public decimal Margemtotalorc { get; set; }
        public decimal Emargemtotalorc { get; set; }
        public decimal Margemtotalreorc { get; set; }
        public decimal Emargemtotalreorc { get; set; }
        public decimal Margemtotaldif { get; set; }
        public decimal Emargemtotaldif { get; set; }
        public decimal Margemorcperc { get; set; }
        public decimal Margemreorcperc { get; set; }
        public string Horasl { get; set; }
        public string Ndosmanual { get; set; }
        public decimal Obranomanual { get; set; }

        //public virtual ICollection<Bo2> ListaBo2 { get; set; }
    }
}